name: Test Coveralls

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
    paths-ignore:
      - '.gitignore'
      - '.php_cs.dist'
      - '.php_cs'
      - 'box.json.dist'
      - 'LICENSE'
      - '**.md'
      - 'docs/**'
      - 'scripts/**'
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            extensions: mbstring
            coverage: pcov
            tools: composer:v2

      -   name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.composer/cache/files
            key: dependencies-php-7.4-composer-${{ hashFiles('composer.json') }}

      -   name: Install dependencies
          run: composer install --prefer-dist --no-interaction --optimize-autoloader

      -   name: Generate Coverage
          run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

#      - name: Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v

