name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [ 7.4, 8.0 ]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: mbstring
            coverage: none
            tools: composer:v2

      -   name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.composer/cache/files
            key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      -   name: Install dependencies
          run: composer install --prefer-dist --no-interaction --optimize-autoloader

      -   name: Execute tests
          run: vendor/bin/phpunit --testdox
